# Cost of living per country

In [83]:
# import libraries
import pandas as pd

In [84]:
cost_living = pd.read_csv('cost-of-living.csv')

In [85]:
cost_living.head()

,Unnamed: 0,"Saint Petersburg, Russia","Istanbul, Turkey","Izmir, Turkey","Helsinki, Finland","Chisinau, Moldova","Milan, Italy","Cairo, Egypt","Banja Luka, Bosnia And Herzegovina","Baku, Azerbaijan",...,"Lviv, Ukraine","Novosibirsk, Russia","Bursa, Turkey","Brussels, Belgium","Jerusalem, Israel","Melbourne, Australia","Perth, Australia","Sydney, Australia","Alexandria, Egypt","Quito, Ecuador"
0,"Meal, Inexpensive Restaurant",7.34,4.58,3.06,12.00,4.67,15.0,3.38,3.58,5.27,...,3.75,5.72,3.82,15.0,15.56,10.22,12.43,11.81,2.81,3.59
1,"Meal for 2 People, Mid-range Restaurant, Three...",29.35,15.28,12.22,65.00,20.74,60.0,17.48,22.99,23.73,...,18.76,22.01,11.47,60.0,62.24,49.54,56.55,54.37,14.06,31.45
2,McMeal at McDonalds (or Equivalent Combo Meal),4.40,3.82,3.06,8.00,4.15,8.0,4.51,3.58,4.22,...,3.56,3.67,3.06,8.2,12.97,7.12,7.32,7.15,3.38,5.39
3,Domestic Beer (0.5 liter draught),2.20,3.06,2.29,6.50,1.04,5.0,1.69,1.02,0.84,...,1.50,1.10,2.37,4.0,7.26,5.57,5.90,4.97,1.69,1.35
4,Imported Beer (0.33 liter bottle),2.20,3.06,2.75,6.75,1.43,5.0,2.82,1.53,2.11,...,1.50,2.20,3.06,4.0,7.26,5.57,5.59,4.97,2.81,2.70

In [86]:
cost_living["Category"]="Grocery"

In [87]:
# Rename Categories in Categry column

# Restaurant
cost_living.loc[(cost_living["Unnamed: 0"] == "Meal, Inexpensive Restaurant") | 
                (cost_living["Unnamed: 0"] == "Meal for 2 People, Mid-range Restaurant, Three-course") |
                (cost_living["Unnamed: 0"] == "McMeal at McDonalds (or Equivalent Combo Meal)")
                , "Category"] = "Restaurant"
# Drink
cost_living.loc[(cost_living["Unnamed: 0"] == "Domestic Beer (0.5 liter draught)") | 
                (cost_living["Unnamed: 0"] == "Imported Beer (0.33 liter bottle)") |
                (cost_living["Unnamed: 0"] == "Coke/Pepsi (0.33 liter bottle)")|
                (cost_living["Unnamed: 0"] == "Water (0.33 liter bottle)")|
                (cost_living["Unnamed: 0"] == "Milk (regular), (1 liter)")|
                (cost_living["Unnamed: 0"] == "Water (1.5 liter bottle)")|
                (cost_living["Unnamed: 0"] == "Bottle of Wine (Mid-Range)")|
                (cost_living["Unnamed: 0"] == "Domestic Beer (0.5 liter bottle)")|
                (cost_living["Unnamed: 0"] == "Imported Beer (0.33 liter bottle)")|
                (cost_living["Unnamed: 0"] == "Cappuccino (regular)")
                , "Category"] = "Drink"



# Cigarettes
cost_living.loc[(cost_living["Unnamed: 0"] == "Cigarettes 20 Pack (Marlboro)")
                , "Category"] = "Cigarettes"

# Public Transport
cost_living.loc[(cost_living["Unnamed: 0"] == "One-way Ticket (Local Transport)") | 
                (cost_living["Unnamed: 0"] == "Monthly Pass (Regular Price)") |
                (cost_living["Unnamed: 0"] == "Taxi Start (Normal Tariff)") |
                (cost_living["Unnamed: 0"] == "Taxi 1km (Normal Tariff)") |
                (cost_living["Unnamed: 0"] == "Taxi 1hour Waiting (Normal Tariff)")
                , "Category"] = "Public Transport"


# Private Transport
cost_living.loc[(cost_living["Unnamed: 0"] == "Gasoline (1 liter)") | 
                (cost_living["Unnamed: 0"] == "Volkswagen Golf") |
                (cost_living["Unnamed: 0"] == "Toyota Corolla 1.6l 97kW Comfort (Or Equivalent New Car)")
                , "Category"] = "Private Transport"

# Apartment Rent
cost_living.loc[(cost_living["Unnamed: 0"] == "Apartment (1 bedroom) in City Centre") | 
                (cost_living["Unnamed: 0"] == "Apartment (1 bedroom) Outside of Centre") |
                (cost_living["Unnamed: 0"] == "Apartment (3 bedrooms) in City Centre")|
                (cost_living["Unnamed: 0"] == "Apartment (3 bedrooms) Outside of Centre")
                , "Category"] = "Apartment Rent"

# Household Expense
cost_living.loc[(cost_living["Unnamed: 0"] == "Basic (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment")
                , "Category"] = "Household Expense"

# Phone
cost_living.loc[(cost_living["Unnamed: 0"] == "Basic (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment")
                , "Category"] = "Phone"

# Fitness
cost_living.loc[(cost_living["Unnamed: 0"] == "Basic (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment")
                , "Category"] = "Fitness"

# Activity
cost_living.loc[(cost_living["Unnamed: 0"] == "Tennis Court Rent (1 Hour on Weekend)")|
                (cost_living["Unnamed: 0"] == "Cinema, International Release, 1 Seat")
                , "Category"] = "Activity"

# Phone&Internet
cost_living.loc[(cost_living["Unnamed: 0"] == "1 min. of Prepaid Mobile Tariff Local (No Discounts or Plans)")|
                (cost_living["Unnamed: 0"] == "Internet (60 Mbps or More, Unlimited Data, Cable/ADSL)")
                , "Category"] = "Phone&Internet"

# School
cost_living.loc[(cost_living["Unnamed: 0"] == "Preschool (or Kindergarten), Full Day, Private, Monthly for 1 Child")|
                (cost_living["Unnamed: 0"] == "International Primary School, Yearly for 1 Child   ")
                , "Category"] = "School"

# Apartment Sale Price
cost_living.loc[(cost_living["Unnamed: 0"] == "Price per Square Meter to Buy Apartment Outside of Centre") | 
                (cost_living["Unnamed: 0"] == "Price per Square Meter to Buy Apartment in City Centre")
                , "Category"] = "Apartment Sale Price"

# Mortgage Interest Rate
cost_living.loc[(cost_living["Unnamed: 0"] == "Mortgage Interest Rate in Percentages (%), Yearly, for 20 Years Fixed-Rate")
                , "Category"] = "Mortgage Interest Rate"

# Net Salary
cost_living.loc[(cost_living["Unnamed: 0"] == "Average Monthly Net Salary (After Tax)")
                , "Category"] = "Net Salary"

# Clothe
cost_living.loc[(cost_living["Unnamed: 0"] == "1 Pair of Jeans (Levis 501 Or Similar)") | 
                (cost_living["Unnamed: 0"] == "1 Summer Dress in a Chain Store (Zara, H&M, ...)") |
                (cost_living["Unnamed: 0"] == "1 Pair of Nike Running Shoes (Mid-Range)")|
                (cost_living["Unnamed: 0"] == "1 Pair of Men Leather Business Shoes")
                , "Category"] = "Clothe"

In [88]:
cost_living["Category"]

0                 Restaurant
1                 Restaurant
2                 Restaurant
3                      Drink
4                      Drink
5                      Drink
6                    Grocery
7                      Drink
8                    Grocery
9                    Grocery
10                   Grocery
11                     Drink
12                     Drink
13                     Drink
14                     Drink
15                Cigarettes
16          Public Transport
17                   Grocery
18          Public Transport
19         Private Transport
20         Private Transport
21            Apartment Rent
22            Apartment Rent
23            Apartment Rent
24            Apartment Rent
25                   Fitness
26            Phone&Internet
27            Phone&Internet
28                   Grocery
29                  Activity
30                  Activity
31                    Clothe
32                    Clothe
33                    Clothe
34                    Clothe
35      Apartment Sale Price
36      Apartment Sale Price
37                Net Salary
38    Mortgage Interest Rate
39          Public Transport
40          Public Transport
41          Public Transport
42                   Grocery
43                   Grocery
44                   Grocery
45                   Grocery
46                     Drink
47                   Grocery
48                   Grocery
49                   Grocery
50                   Grocery
51                   Grocery
52         Private Transport
53                    School
54                   Grocery
Name: Category, dtype: object

In [108]:
cost_living.iloc[0]

Unnamed: 0                  Meal, Inexpensive Restaurant
Saint Petersburg, Russia                            7.34
Istanbul, Turkey                                    4.58
Izmir, Turkey                                       3.06
Helsinki, Finland                                     12
                                        ...
Perth, Australia                                   12.43
Sydney, Australia                                  11.81
Alexandria, Egypt                                   2.81
Quito, Ecuador                                      3.59
Category                                      Restaurant
Name: 0, Length: 162, dtype: object

In [93]:
cost_living.shape

(55, 162)

In [89]:
# save new csv as cost_living_clean
cost_living.to_csv('cost_living_clean.csv')

In [106]:
cost_living.groupby("Category").mean()

,"Saint Petersburg, Russia","Istanbul, Turkey","Izmir, Turkey","Helsinki, Finland","Chisinau, Moldova","Milan, Italy","Cairo, Egypt","Banja Luka, Bosnia And Herzegovina","Baku, Azerbaijan","Guadalajara, Mexico",...,"Lviv, Ukraine","Novosibirsk, Russia","Bursa, Turkey","Brussels, Belgium","Jerusalem, Israel","Melbourne, Australia","Perth, Australia","Sydney, Australia","Alexandria, Egypt","Quito, Ecuador"
Category,,,,,,,,,,,,,,,,,,,,,
Activity,11.735000,9.740000,7.365000,19.360000,8.645000,16.480000,5.790000,5.965000,10.210000,6.645000,...,6.295000,10.855000,5.635000,13.970000,13.485000,13.260000,11.590000,12.965000,5.590000,11.060000
Apartment Rent,624.110000,332.437500,229.920000,1208.885000,295.490000,1392.875000,219.947500,259.237500,339.100000,379.922500,...,404.577500,403.070000,204.532500,1018.310000,1112.590000,1340.835000,998.607500,1798.425000,170.385000,429.687500
Apartment Sale Price,1991.875000,986.115000,682.340000,5771.950000,746.975000,5970.730000,551.350000,1168.255000,977.465000,969.195000,...,895.930000,1031.055000,479.745000,2885.120000,6341.985000,5384.825000,3436.365000,6905.395000,481.805000,1167.740000
Cigarettes,2.200000,2.750000,2.290000,7.700000,1.560000,5.500000,2.260000,2.810000,2.110000,2.480000,...,1.540000,1.910000,2.290000,6.700000,9.080000,19.010000,18.640000,20.820000,2.250000,4.490000
Clothe,71.427500,43.487500,37.655000,79.570000,68.135000,85.392500,64.650000,59.525000,63.307500,49.062500,...,70.727500,68.485000,37.745000,75.290000,87.997500,64.447500,63.280000,70.192500,59.222500,67.687500
Drink,1.930000,2.394444,1.997778,4.384444,1.265556,2.863333,2.417778,1.272222,1.575556,1.947778,...,1.323333,1.721111,2.236667,2.851111,4.194444,3.738889,3.902222,3.882222,1.961111,2.651111
Fitness,102.170000,59.330000,51.070000,82.660000,113.460000,163.970000,25.790000,141.040000,42.650000,22.640000,...,88.450000,94.510000,67.460000,122.980000,166.880000,127.870000,129.020000,110.700000,18.560000,39.640000
Grocery,340.278125,434.927500,312.171875,107.831875,170.643750,680.578750,176.816250,87.206250,356.741875,179.914375,...,173.126875,158.150625,255.509375,1151.593125,258.876875,810.382500,725.587500,751.917500,135.901875,405.101875
Mortgage Interest Rate,10.290000,19.080000,22.230000,1.380000,9.420000,1.950000,13.420000,4.460000,8.210000,11.240000,...,18.960000,10.790000,19.050000,1.680000,3.750000,4.110000,4.310000,3.820000,16.170000,10.710000
Net Salary,645.940000,436.000000,392.070000,2382.560000,286.950000,1601.000000,221.700000,430.690000,294.030000,498.680000,...,341.380000,436.280000,443.850000,2289.690000,1911.120000,2791.960000,2493.770000,3018.360000,163.940000,527.180000
Phone&Internet,3.495000,7.155000,6.490000,11.190000,4.325000,14.555000,7.390000,10.720000,7.770000,13.795000,...,2.235000,3.995000,6.525000,21.830000,12.145000,21.700000,22.050000,21.945000,8.290000,18.440000
Private Transport,12865.116667,15106.306667,15114.340000,15468.103333,11191.410000,15211.640000,15373.113333,11130.276667,11374.493333,10705.103333,...,13680.593333,12108.703333,14613.930000,13996.590000,23051.046667,10234.206667,10463.350000,10304.350000,15566.326667,15629.700000
Public Transport,9.856000,7.310000,5.614000,23.308000,2.804000,15.088000,2.650000,6.570000,2.506000,5.630000,...,2.206000,3.492000,5.470000,17.210000,16.412000,24.694000,24.246000,34.426000,2.280000,7.142000
Restaurant,13.696667,7.893333,6.113333,28.333333,9.853333,27.666667,8.456667,10.050000,11.073333,11.120000,...,8.690000,10.466667,6.116667,27.733333,30.256667,22.293333,25.433333,24.443333,6.750000,13.476667
School,411.830000,282.940000,212.180000,351.600000,210.520000,617.270000,121.150000,128.700000,208.840000,145.750000,...,192.510000,222.830000,200.510000,695.440000,566.180000,1250.410000,1190.120000,1389.430000,55.410000,276.630000

In [90]:
# open csv & # transforme data so we have the rows as cities(location)
cost_living_clean = pd.read_csv('cost_living_clean.csv', index_col=[0]).T.reset_index()

In [104]:
cost_living_clean.groupby(50).sum().T

50,0.25,0.28,0.31,0.33,0.34,0.35,0.36,0.37,0.39,0.41,...,2.32,2.39,2.47,2.69,2.83,2.87,3.07,3.4,Grocery,Onion (1kg)
index,"Tashkent, Uzbekistan","Almaty, Kazakhstan","Alexandria, Egypt","Ahmedabad, IndiaHyderabad, India","Cairo, EgyptDelhi, India","Noida, India","Gurgaon, IndiaKolkata, IndiaNovosibirsk, Russia","Tbilisi, GeorgiaMumbai, IndiaPune, India","Baku, AzerbaijanKharkiv, UkraineChandigarh, India","Kathmandu, NepalYekaterinburg, RussiaBangalore...",...,"Seattle, WA, United States","Chicago, IL, United States","San Francisco, CA, United States","Zurich, Switzerland","Seoul, South Korea","Tokyo, Japan","New York, NY, United States","Boston, MA, United States",Category,Unnamed: 0.1
0,3.59,4.77,2.81,3.8,7.18,3.8,12.05,11.63,12.31,14.15,...,13.48,13.47,15.95,23.12,6.42,8.19,17.97,13.47,Restaurant,"Meal, Inexpensive Restaurant"
1,15.72,23.84,14.06,17.72,32.67,12.66,45.43,46.54,52.65,72.76,...,62.89,53.87,71.88,92.46,31.11,40.97,76.37,62.85,Restaurant,"Meal for 2 People, Mid-range Restaurant, Three..."
2,2.7,3.81,3.38,6.96,7.67,3.16,10.62,11.01,11.27,16.4,...,7.19,7.18,8.98,12.94,5.06,5.7,8.09,7.18,Restaurant,McMeal at McDonalds (or Equivalent Combo Meal)
3,0.9,1.07,1.69,3.42,3.59,1.39,4.93,5.49,3.62,7.25,...,5.39,4.94,6.29,6.24,3.11,4.1,6.29,6.29,Drink,Domestic Beer (0.5 liter draught)
4,1.8,1.43,2.81,6.33,5.92,2.53,8.84,8.71,6.57,11.42,...,5.84,6.29,7.19,5.55,4.67,4.92,7.19,6.73,Drink,Imported Beer (0.33 liter bottle)
5,0.54,0.4,0.32,0.81,0.71,0.39,1.43,1.28,1.1,2.14,...,1.97,1.75,2.26,3.87,1.33,1.2,1.85,1.75,Drink,Coke/Pepsi (0.33 liter bottle)
6,0.21,0.31,0.19,0.37,0.37,0.17,0.86,0.53,0.72,1.29,...,1.52,1.52,1.72,3.21,0.75,0.87,1.59,1.53,Grocery,Water (0.33 liter bottle)
7,0.64,0.75,0.81,1.26,1.48,0.61,1.98,2.28,2.38,2.8,...,0.77,0.7,0.98,1.58,1.95,1.55,1.04,0.78,Drink,"Milk (regular), (1 liter)"
8,0.15,0.24,0.51,0.9,0.91,0.4,1.18,1.13,1.11,1.76,...,2.76,2.54,3.12,2.88,2.47,1.54,3.33,2.62,Grocery,Loaf of Fresh White Bread (500g)
9,0.92,0.9,1.02,1.61,1.91,0.84,2.79,2.81,2.81,4.23,...,2.4,2.05,2.82,5.33,2.67,1.95,3.28,2.34,Grocery,Eggs (regular) (12)
10,3.73,5.87,3.68,10.94,7.38,2.96,15.96,14.26,14.88,25.15,...,14.42,9.95,15.47,22.63,17.41,9.64,14.21,12.75,Grocery,Local Cheese (1kg)
11,0.28,0.42,0.26,0.72,0.66,0.37,1.2,1.09,1.25,1.56,...,1.68,2.08,1.74,1.13,1.17,1.07,2.07,1.58,Drink,Water (1.5 liter bottle)
12,2.7,4.77,7.03,16.45,20.21,9.65,23.58,19.54,21.2,25.36,...,13.48,12.57,13.48,12.02,15.55,9.01,13.48,13.02,Drink,Bottle of Wine (Mid-Range)
13,0.51,0.56,1.31,3.03,2.76,1.34,3.92,4.04,3.13,4.83,...,1.83,1.82,2.04,1.79,2.15,2.22,2.07,2.01,Drink,Domestic Beer (0.5 liter bottle)
14,1.46,1.1,1.97,5.35,4.45,2.17,6.61,6.91,5.88,8.14,...,2.19,1.88,1.98,2.55,2.23,3.45,2.43,2.32,Drink,Imported Beer (0.33 liter bottle)
15,1.17,0.95,2.25,6.96,6.06,3.16,9.51,9.16,7.35,9.24,...,9.66,11.67,10.78,7.86,3.5,4.1,13.48,9.88,Cigarettes,Cigarettes 20 Pack (Marlboro)
16,0.13,0.19,0.23,0.5,0.66,0.51,0.96,0.66,0.71,1.21,...,2.47,2.24,2.47,3.88,0.97,1.56,2.47,2.22,Public Transport,One-way Ticket (Local Transport)
17,2.35,3.12,4.07,6.41,7.53,3,9.7,9.11,9.98,14.16,...,11.23,9.53,12.11,25.23,7.48,6.56,12.37,11,Grocery,"Chicken Breasts (Boneless, Skinless), (1kg)"
18,13.48,17.16,8.44,17.08,23.94,12.66,28.09,25.8,27.4,58.02,...,88.95,94.28,72.78,78.59,42.78,81.95,114.11,80.81,Public Transport,Monthly Pass (Regular Price)
19,0.46,0.39,0.39,1.89,1.39,0.94,2.54,2.78,2.49,3.64,...,0.84,0.74,0.95,1.53,1.18,1.14,0.71,0.66,Private Transport,Gasoline (1 liter)
20,17071.2,15494.6,23626.7,22274.7,35223.5,10124.9,39711.5,31491.2,48857.1,81931.4,...,22462.1,19614.7,19802.6,22606.8,24887.5,20769.5,19627.4,19789.8,Private Transport,Volkswagen Golf
21,209.86,288.22,142.04,356.12,388.32,153.28,721.52,1027.73,785.69,1066.44,...,1919.17,1702.25,3131.06,1701.77,714.76,1013.36,2854.26,2275.95,Apartment Rent,Apartment (1 bedroom) in City Centre
22,124.02,178.04,84.65,242.01,232.95,94.92,450.7,575.32,464.7,707.8,...,1450.04,1100.17,2527.11,1263.69,465.05,636.07,1788.76,1716.68,Apartment Rent,Apartment (1 bedroom) Outside of Centre
23,449.24,565.15,285.82,759.03,844.01,344.64,1527.74,2469.37,1585.67,1980.59,...,3199.48,3168.97,5661.53,3099.86,1903.9,2270.89,5574.89,3574.7,Apartment Rent,Apartment (3 bedrooms) in City Centre
24,239.9,357.57,169.03,489.61,520.96,208.55,941.79,1216.42,912.04,1310.76,...,2321.44,1953.12,4320.95,2296.54,1036.41,1221.64,3314.05,2503.07,Apartment Rent,Apartment (3 bedrooms) Outside of Centre
25,31.53,58.48,18.56,69.73,77.47,61.65,187.51,126.79,220.55,248.74,...,144.15,117.08,127.73,162.87,150.79,162.41,116.65,119.59,Fitness,"Basic (Electricity, Heating, Cooling, Water, G..."
26,0.02,0.03,0.01,0.02,0.02,0.01,0.05,0.1,0.07,0.08,...,0.09,0.16,0.09,0.26,0.11,0.37,0.09,0.08,Phone&Internet,1 min. of Prepaid Mobile Tariff Local (No Disc...
27,35.48,10.47,16.57,16.81,24.53,11.58,28.49,34.88,31.81,41.13,...,58.46,57.23,60,48.71,19.76,38.33,55.18,61.7,Phone&Internet,"Internet (60 Mbps or More, Unlimited Data, Cab..."
28,24.77,39.41,19.58,36.28,47.54,22.23,71.82,71,67.6,96.69,...,48.94,42.52,77.08,76.33,55.64,77.29,67.04,51.97,Grocery,"Fitness Club, Monthly Fee for 1 Adult"
29,5.75,9.43,7.52,14.94,14.36,10.76,31.92,22.53,31.47,38.83,...,26.51,23.05,16.81,32.9,17.57,26.39,30.1,15.39,Activity,Tennis Court Rent (1 Hour on Weekend)
30,3.59,3.58,3.66,5.69,8.31,3.8,11.99,11.83,10.61,14.29,...,13.48,11.67,13.48,16.64,7.78,14.75,14.38,13.47,Activity,"Cinema, International Release, 1 Seat"
31,35.25,44.78,32.34,52.36,72.94,29.16,129,117.82,141.02,176.46,...,42.55,45.28,55.68,106.93,58.75,58.4,47.04,43.34,Clothe,1 Pair of Jeans (Levis 501 Or Similar)
32,32.67,38.14,40.48,57.45,77.86,33.33,112.62,91.41,124.1,133.87,...,35.25,35.06,38.39,46.47,41.24,37.28,34.37,27.76,Clothe,"1 Summer Dress in a Chain Store (Zara, H&M, ...)"
33,68.86,74.49,114.49,84.45,162.85,52.08,178.05,167.04,234.12,252.22,...,75.86,73,77.2,111.39,75.4,71.31,75.39,71.03,Clothe,1 Pair of Nike Running Shoes (Mid-Range)
34,61.57,86.52,49.58,61.3,94.57,33.12,156.1,155.77,218.19,262.3,...,111.44,96.56,134.75,171.22,119.08,120.05,113.98,91.75,Clothe,1 Pair of Men Leather Business Shoes
35,802.53,1119.15,672.49,1746.29,2479.18,874.62,3839.39,8480.46,3685.15,5401.8,...,6588.64,3656.41,11670.7,11400.6,13807.2,9581.79,13179.5,8867.39,Apartment Sale Price,Price per Square Meter to Buy Apartment in Cit...
36,390.61,691.71,291.12,935.53,1264.48,585.38,2264.47,3719.94,1867.19,2845.92,...,4065,1816.95,8658.93,7405.74,6552.41,5268.04,6891.37,4036.93,Apartment Sale Price,Price per Square Meter to Buy Apartment Outsid...
37,205.98,374.42,163.94,744.66,695.5,536.67,1618.67,1267.12,1011.7,1642.76,...,4741.65,3717.02,6532.21,5714.8,2120.34,2657.42,4665.46,4132.08,Net Salary,Average Monthly Net Salary (After Tax)
38,18.36,15.4,16.17,19.28,22.65,9.21,29.14,30.85,36.66,49.77,...,4.14,4.23,4.18,1.57,3.56,1.46,4.17,4.22,Mortgage Interest Rate,"Mortgage Interest Rate in Percentages (%), Yea..."
39,0.54,0.95,0.34,1.26,1.02,0.63,2.59,1.84,2.97,5.97,...,2.34,2.92,3.14,6.47,2.96,3.91,2.7,2.69,Public Transport,Taxi Start (Normal Tariff)
40,0.18,0.35,0.14,0.38,0.36,0.15,0.53,0.74,0.73,1.3,...,1.51,1.26,1.95,4.16,0.59,3.44,1.59,1.67,Public Transport,Taxi 1km (Normal Tariff)
41,2.31,2.62,2.25,1.84,1.89,0.76,6.3,4.1,5.98,10.07,...,26.95,21.55,29.65,73.78,9.33,28.64,26.95,25.14,Public Transport,Taxi 1hour Waiting (Normal Tariff)
42,0.93,1.04,1.48,3.42,2.94,1.81,5.13,4.64,3.05,5.82,...,4.69,4.47,4.38,3.82,6.7,6.58,5.63,3.96,Grocery,Apples (1kg)
43,2.22,1.4,0.4,1.75,1.15,0.86,3.24,3.14,3.33,4.42,...,3.38,3.69,3.11,4.1,5.79,5.02,5.7,4.17,Grocery,Oranges (1kg)
44,0.38,0.37,0.37,0.63,0.76,0.26,0.94,1.04,1.13,1.49,...,2.3,2.22,3.49,2.75,3.8,3.2,3.81,1.79,Grocery,Potato (1kg)
45,0.21,1.25,0.2,1.06,0.71,0.59,1.55,1.59,1.64,1.96,...,1.73,1.42,1.17,2.58,2.24,1.62,1.94,1.68,Grocery,Lettuce (1 head)
46,1.11,1.78,1.45,2.57,3.29,1.45,4.97,4.93,4.57,5.97,...,3.81,3.69,4.06,4.66,3.72,3.21,4.22,3.6,Drink,Cappuccino (regular)
47,0.82,0.8,0.66,1.39,1.44,1.02,2.44,2.34,2.92,3.32,...,4.1,3.92,4.15,2.52,3.61,5.04,5.7,3.68,Grocery,"Rice (white), (1kg)"
48,0.63,1.09,0.39,0.85,0.8,0.45,2.72,1.81,2.21,3.54,...,4.28,3.52,4.33,3.79,5.76,5.19,5.33,5.14,Grocery,Tomato (1kg)
49,1.79,1.23,0.66,1.05,1.33,0.7,2.41,2.46,2.96,3.68,...,1.67,1.47,1.79,2.89,3.5,2.81,2.17,1.39,Grocery,Banana (1kg)
51,4.76,5.49,8.37,9.86,13.25,4.51,17.39,14.13,16.94,21.25,...,13.11,12.4,14.53,46.09,29.31,19.66,13.56,14.07,Grocery,Beef Round (1kg) (or Equivalent Back Leg Red M...
52,19227.6,17285.5,23071.9,42155.3,42370.6,20946.7,59998.4,52981.1,60770.3,107828,...,20472.6,18842.7,20177.7,21450,21511.4,18110.3,18118.4,18411,Private Transport,Toyota Corolla 1.6l 97kW Comfort (Or Equivalen...
53,125.64,153.08,55.41,111.66,189.86,87.89,363.98,232.16,433.69,535.99,...,1568.61,1025.73,1959.36,2194.64,323.08,604.02,2106.38,1534.76,School,"Preschool (or Kindergarten), Full Day, Private..."
54,3996.17,4428.44,2132.54,2934.64,4456.12,2190.01,6113.44,5452.21,9434.65,9522.79,...,19730.7,15972.6,25657.7,28414.1,16410.4,17051.3,34441.9,24642.5,Grocery,"International Primary School, Yearly for 1 Child"

In [103]:
cost_living_clean.loc

In [81]:
# data needs to be transformed so we have the rows are cities.
cost_living_clean = cost_living_clean.rename(columns={'index':'location'})
cost_living_clean.head()

,location,0,1,2,3,4,5,6,7,8,...,45,46,47,48,49,50,51,52,53,54
0,Unnamed: 0.1,"Meal, Inexpensive Restaurant","Meal for 2 People, Mid-range Restaurant, Three...",McMeal at McDonalds (or Equivalent Combo Meal),Domestic Beer (0.5 liter draught),Imported Beer (0.33 liter bottle),Coke/Pepsi (0.33 liter bottle),Water (0.33 liter bottle),"Milk (regular), (1 liter)",Loaf of Fresh White Bread (500g),...,Lettuce (1 head),Cappuccino (regular),"Rice (white), (1kg)",Tomato (1kg),Banana (1kg),Onion (1kg),Beef Round (1kg) (or Equivalent Back Leg Red M...,Toyota Corolla 1.6l 97kW Comfort (Or Equivalen...,"Preschool (or Kindergarten), Full Day, Private...","International Primary School, Yearly for 1 Child"
1,"Saint Petersburg, Russia",7.34,29.35,4.4,2.2,2.2,0.76,0.53,0.98,0.71,...,0.86,1.96,0.92,1.91,0.89,0.48,7.18,19305.3,411.83,5388.86
2,"Istanbul, Turkey",4.58,15.28,3.82,3.06,3.06,0.64,0.24,0.71,0.36,...,0.61,1.84,1.3,0.8,1.91,0.62,9.73,20874.7,282.94,6905.43
3,"Izmir, Turkey",3.06,12.22,3.06,2.29,2.75,0.61,0.22,0.65,0.38,...,0.57,1.56,1.31,0.7,1.78,0.58,8.61,20898.8,212.18,4948.41
4,"Helsinki, Finland",12,65,8,6.5,6.75,2.66,1.89,0.96,2.27,...,2.3,3.87,2.13,2.91,1.61,1.25,12.34,24402.8,351.6,1641

In [117]:
cost_living

,Unnamed: 0,"Saint Petersburg, Russia","Istanbul, Turkey","Izmir, Turkey","Helsinki, Finland","Chisinau, Moldova","Milan, Italy","Cairo, Egypt","Banja Luka, Bosnia And Herzegovina","Baku, Azerbaijan",...,"Novosibirsk, Russia","Bursa, Turkey","Brussels, Belgium","Jerusalem, Israel","Melbourne, Australia","Perth, Australia","Sydney, Australia","Alexandria, Egypt","Quito, Ecuador",Category
0,"Meal, Inexpensive Restaurant",7.34,4.58,3.06,12.00,4.67,15.00,3.38,3.58,5.27,...,5.72,3.82,15.00,15.56,10.22,12.43,11.81,2.81,3.59,Restaurant
1,"Meal for 2 People, Mid-range Restaurant, Three...",29.35,15.28,12.22,65.00,20.74,60.00,17.48,22.99,23.73,...,22.01,11.47,60.00,62.24,49.54,56.55,54.37,14.06,31.45,Restaurant
2,McMeal at McDonalds (or Equivalent Combo Meal),4.40,3.82,3.06,8.00,4.15,8.00,4.51,3.58,4.22,...,3.67,3.06,8.20,12.97,7.12,7.32,7.15,3.38,5.39,Restaurant
3,Domestic Beer (0.5 liter draught),2.20,3.06,2.29,6.50,1.04,5.00,1.69,1.02,0.84,...,1.10,2.37,4.00,7.26,5.57,5.90,4.97,1.69,1.35,Drink
4,Imported Beer (0.33 liter bottle),2.20,3.06,2.75,6.75,1.43,5.00,2.82,1.53,2.11,...,2.20,3.06,4.00,7.26,5.57,5.59,4.97,2.81,2.70,Drink
5,Coke/Pepsi (0.33 liter bottle),0.76,0.64,0.61,2.66,0.64,2.49,0.29,1.18,0.37,...,0.69,0.70,2.47,2.07,1.91,1.79,1.99,0.32,0.71,Drink
6,Water (0.33 liter bottle),0.53,0.24,0.22,1.89,0.44,1.12,0.18,0.74,0.21,...,0.52,0.23,2.07,1.71,1.70,1.62,1.68,0.19,0.47,Grocery
7,"Milk (regular), (1 liter)",0.98,0.71,0.65,0.96,0.68,1.21,0.84,0.69,0.83,...,0.85,0.69,0.97,1.43,0.90,1.03,0.90,0.81,0.87,Drink
8,Loaf of Fresh White Bread (500g),0.71,0.36,0.38,2.27,0.33,1.94,0.51,0.63,0.26,...,0.49,0.42,1.64,1.54,1.88,1.76,1.85,0.51,1.35,Grocery
9,Eggs (regular) (12),1.18,1.62,1.51,2.02,1.11,2.87,1.04,1.47,1.03,...,1.00,1.63,2.65,3.32,2.85,2.59,2.79,1.02,1.59,Grocery
10,Local Cheese (1kg),7.60,5.32,4.97,6.87,5.79,13.54,3.16,4.76,3.54,...,7.30,5.93,13.14,10.63,6.12,6.52,7.68,3.68,5.47,Grocery
11,Water (1.5 liter bottle),0.63,0.33,0.29,1.54,0.59,0.40,0.29,0.48,0.43,...,0.50,0.29,0.94,1.50,1.28,1.68,1.29,0.26,0.93,Drink
12,Bottle of Wine (Mid-Range),5.87,7.64,6.11,12.00,3.61,7.00,10.72,4.34,4.75,...,5.87,7.65,7.00,10.37,9.29,9.32,11.19,7.03,11.68,Drink
13,Domestic Beer (0.5 liter bottle),0.88,1.79,1.63,2.23,0.77,1.20,1.40,0.50,0.76,...,0.90,1.64,1.24,2.02,3.13,2.99,3.42,1.31,1.26,Drink
14,Imported Beer (0.33 liter bottle),1.89,2.48,2.09,2.95,1.38,2.01,2.06,0.86,1.94,...,1.50,2.14,1.87,3.04,3.37,3.96,3.73,1.97,2.55,Drink
15,Cigarettes 20 Pack (Marlboro),2.20,2.75,2.29,7.70,1.56,5.50,2.26,2.81,2.11,...,1.91,2.29,6.70,9.08,19.01,18.64,20.82,2.25,4.49,Cigarettes
16,One-way Ticket (Local Transport),0.59,0.41,0.46,2.80,0.10,2.00,0.28,0.92,0.16,...,0.32,0.51,2.10,1.53,2.72,2.58,2.73,0.23,0.22,Public Transport
17,"Chicken Breasts (Boneless, Skinless), (1kg)",3.96,3.50,3.05,9.42,3.55,8.83,4.18,3.97,2.92,...,3.88,3.15,9.07,8.33,6.64,6.90,7.15,4.07,6.01,Grocery
18,Monthly Pass (Regular Price),42.56,31.32,22.92,59.70,9.33,39.00,11.28,22.48,9.63,...,11.01,22.95,49.00,55.23,95.36,84.02,130.49,8.44,23.81,Public Transport
19,Gasoline (1 liter),0.67,1.05,1.04,1.54,0.98,1.59,0.45,1.17,0.49,...,0.64,1.05,1.44,1.67,0.91,0.87,0.93,0.39,0.54,Private Transport
20,Volkswagen Golf,19289.39,24443.15,24443.15,22000.00,16335.12,22400.00,25098.60,16859.68,15558.40,...,18196.16,22948.67,20200.00,34229.98,15479.87,16149.98,15845.50,23626.73,21563.64,Private Transport
21,Apartment (1 bedroom) in City Centre,524.45,291.55,212.22,986.93,244.49,1099.67,188.00,219.72,290.07,...,344.85,177.53,838.20,919.40,1134.86,897.50,1568.39,142.04,369.07,Apartment Rent
22,Apartment (1 bedroom) Outside of Centre,344.27,177.72,128.36,758.13,177.96,731.69,109.76,159.73,157.97,...,225.13,121.74,686.19,740.05,859.46,639.56,1140.67,84.65,221.89,Apartment Rent
23,Apartment (3 bedrooms) in City Centre,1012.53,545.50,353.76,1819.32,428.67,2311.84,352.74,398.18,608.91,...,635.89,315.38,1432.14,1577.52,2027.71,1474.61,2674.32,285.82,680.28,Apartment Rent
24,Apartment (3 bedrooms) Outside of Centre,615.19,314.98,225.34,1271.16,330.84,1428.30,229.29,259.32,299.45,...,406.41,203.48,1116.71,1213.39,1341.31,982.76,1810.32,169.03,447.51,Apartment Rent
25,"Basic (Electricity, Heating, Cooling, Water, G...",102.17,59.33,51.07,82.66,113.46,163.97,25.79,141.04,42.65,...,94.51,67.46,122.98,166.88,127.87,129.02,110.70,18.56,39.64,Fitness
26,1 min. of Prepaid Mobile Tariff Local (No Disc...,0.03,0.11,0.09,0.07,0.07,0.18,0.01,0.10,0.03,...,0.03,0.12,0.23,0.13,0.12,0.32,0.38,0.01,0.11,Phone&Internet
27,"Internet (60 Mbps or More, Unlimited Data, Cab...",6.96,14.20,12.89,22.31,8.58,28.93,14.77,21.34,15.51,...,7.96,12.93,43.43,24.16,43.28,43.78,43.51,16.57,36.77,Phone&Internet
28,"Fitness Club, Monthly Fee for 1 Adult",26.27,25.10,20.64,34.54,26.64,66.62,26.19,20.70,30.43,...,27.49,23.40,26.11,71.27,46.28,39.32,47.37,19.58,40.91,Grocery
29,Tennis Court Rent (1 Hour on Weekend),18.33,15.66,11.67,24.72,12.10,22.96,7.07,9.38,16.73,...,17.31,8.21,16.94,16.60,14.14,11.99,13.50,7.52,16.73,Activity
30,"Cinema, International Release, 1 Seat",5.14,3.82,3.06,14.00,5.19,10.00,4.51,2.55,3.69,...,4.40,3.06,11.00,10.37,12.38,11.19,12.43,3.66,5.39,Activity
31,1 Pair of Jeans (Levis 501 Or Similar),71.86,36.15,33.20,83.41,56.54,86.65,42.38,63.44,43.59,...,65.73,29.38,72.59,81.25,61.86,57.64,61.22,32.34,56.57,Clothe
32,"1 Summer Dress in a Chain Store (Zara, H&M, ...)",38.25,25.91,22.48,31.41,35.37,32.80,44.32,26.64,40.16,...,43.52,17.75,33.81,56.11,36.07,32.49,38.11,40.48,41.74,Clothe
33,1 Pair of Nike Running Shoes (Mid-Range),74.88,61.31,52.74,82.49,86.25,86.32,114.98,73.77,93.36,...,82.60,57.01,78.65,104.25,75.79,76.64,86.50,114.49,88.39,Clothe
34,1 Pair of Men Leather Business Shoes,100.72,50.58,42.20,120.97,94.38,135.80,56.92,74.25,76.12,...,82.09,46.84,116.11,110.38,84.07,86.35,94.94,49.58,84.05,Clothe
35,Price per Square Meter to Buy Apartment in Cit...,2476.05,1315.18,856.54,7444.54,904.82,8221.95,695.67,1328.34,1307.40,...,1273.80,573.51,3232.14,7929.81,5967.57,4005.94,8435.22,672.49,1388.16,Apartment Sale Price
36,Price per Square Meter to Buy Apartment Outsid...,1507.70,657.05,508.14,4099.36,589.13,3719.51,407.03,1008.17,647.53,...,788.31,385.98,2538.10,4754.16,4802.08,2866.79,5375.57,291.12,947.32,Apartment Sale Price
37,Average Monthly Net Salary (After Tax),645.94,436.00,392.07,2382.56,286.95,1601.00,221.70,430.69,294.03,...,436.28,443.85,2289.69,1911.12,2791.96,2493.77,3018.36,163.94,527.18,Net Salary
38,"Mortgage Interest Rate in Percentages (%), Yea...",10.29,19.08,22.23,1.38,9.42,1.95,13.42,4.46,8.21,...,10.79,19.05,1.68,3.75,4.11,4.31,3.82,16.17,10.71,Mortgage Interest Rate
39,Taxi Start (Normal Tariff),1.47,0.76,0.61,6.00,1.30,5.00,0.39,1.02,0.84,...,1.58,0.64,3.00,3.11,3.10,3.11,2.49,0.34,1.35,Public Transport
40,Taxi 1km (Normal Tariff),0.26,0.47,0.57,1.00,0.18,1.12,0.17,0.77,0.32,...,0.15,0.50,1.95,0.95,1.11,1.07,1.37,0.14,1.35,Public Transport
41,Taxi 1hour Waiting (Normal Tariff),4.40,3.59,3.51,47.04,3.11,28.32,1.13,7.66,1.58,...,4.40,2.75,30.00,21.24,21.18,30.45,35.05,2.25,8.98,Public Transport
42,Apples (1kg),1.29,0.85,0.77,2.10,0.70,2.13,1.31,0.86,0.69,...,1.48,0.81,2.17,2.76,2.56,2.41,2.77,1.48,2.07,Grocery
43,Oranges (1kg),1.25,0.86,0.73,1.75,1.22,2.05,0.39,1.18,1.26,...,1.26,0.81,2.24,1.35,2.15,2.15,2.38,0.40,1.32,Grocery
44,Potato (1kg),0.56,0.59,0.52,0.91,0.56,1.28,0.47,0.55,0.46,...,0.37,0.50,1.50,0.89,2.24,1.54,2.08,0.37,1.02,Grocery
45,Lettuce (1 head),0.86,0.61,0.57,2.30,0.84,1.27,0.28,0.55,0.42,...,0.63,0.53,1.29,1.19,1.57,1.26,1.59,0.20,0.58,Grocery
46,Cappuccino (regular),1.96,1.84,1.56,3.87,1.25,1.46,1.65,0.85,2.15,...,1.88,1.59,3.17,2.80,2.63,2.86,2.48,1.45,1.81,Drink
47,"Rice (white), (1kg)",0.92,1.30,1.31,2.13,0.93,2.25,0.65,1.05,1.05,...,0.95,1.40,2.19,2.06,1.58,1.96,1.65,0.66,1.34,Grocery
48,Tomato (1kg),1.91,0.80,0.70,2.91,1.56,2.45,0.35,0.94,0.83,...,1.80,0.79,2.07,1.31,3.06,2.40,3.01,0.39,1.06,Grocery
49,Banana (1kg),0.89,1.91,1.78,1.61,1.37,1.99,0.66,1.06,1.22,...,1.10,1.73,1.63,1.78,2.20,2.11,2.17,0.66,0.99,Grocery
50,Onion (1kg),0.48,0.62,0.58,1.25,0.59,1.27,0.34,0.64,0.39,...,0.36,0.55,1.30,0.94,1.78,1.29,1.72,0.31,0.94,Grocery
51,Beef Round (1kg) (or Equivalent Back Leg Red M...,7.18,9.73,8.61,12.34,5.37,17.75,8.06,7.43,6.15,...,7.20,10.08,13.56,13.52,9.42,9.49,11.24,8.37,6.46,Grocery
52,Toyota Corolla 1.6l 97kW Comfort (Or Equivalen...,19305.29,20874.72,20898.83,24402.77,17238.13,23233.33,21020.29,16529.98,18564.59,...,18129.31,20892.07,21788.33,34921.49,15221.84,15239.20,15066.62,23071.86,25324.92,Private Transport
53,"Preschool (or Kindergarten), Full Day, Private...",411.83,282.94,212.18,351.60,210.52,617.27,121.15,128.70,208.84,...,222.83,200.51,695.44,566.18,1250.41,1190.12,1389.43,55.41,276.63,School
54,"International Primary School, Yearly for 1 Child",5388.86,6905.43,4948.41,1641.00,2679.30,10761.90,2781.29,1348.77,5657.01,...,2474.58,4036.19,18342.86,4019.43,12874.09,11526.08,11933.55,2132.54,6410.05,Grocery

In [82]:
# separamos de la columna location Country y City
cost_living["Country"]=cost_living["location"].str.split(",").str[-1]

KeyError: 'location'

In [6]:
cost_living["City"]=cost_living["location"].str.split(",").str[0]

In [7]:
cost_living.columns

Index(['location', 'Meal, Inexpensive Restaurant',
       'Meal for 2 People, Mid-range Restaurant, Three-course',
       'McMeal at McDonalds (or Equivalent Combo Meal)',
       'Domestic Beer (0.5 liter draught)',
       'Imported Beer (0.33 liter bottle)', 'Coke/Pepsi (0.33 liter bottle)',
       'Water (0.33 liter bottle) ', 'Milk (regular), (1 liter)',
       'Loaf of Fresh White Bread (500g)', 'Eggs (regular) (12)',
       'Local Cheese (1kg)', 'Water (1.5 liter bottle)',
       'Bottle of Wine (Mid-Range)', 'Domestic Beer (0.5 liter bottle)',
       'Imported Beer (0.33 liter bottle)', 'Cigarettes 20 Pack (Marlboro)',
       'One-way Ticket (Local Transport)',
       'Chicken Breasts (Boneless, Skinless), (1kg)',
       'Monthly Pass (Regular Price)', 'Gasoline (1 liter)', 'Volkswagen Golf',
       'Apartment (1 bedroom) in City Centre',
       'Apartment (1 bedroom) Outside of Centre',
       'Apartment (3 bedrooms) in City Centre',
       'Apartment (3 bedrooms) Outside of Centre',
       'Basic (Electricity, Heating, Cooling, Water, Garbage) for 85m2 Apartment',
       '1 min. of Prepaid Mobile Tariff Local (No Discounts or Plans)',
       'Internet (60 Mbps or More, Unlimited Data, Cable/ADSL)',
       'Fitness Club, Monthly Fee for 1 Adult',
       'Tennis Court Rent (1 Hour on Weekend)',
       'Cinema, International Release, 1 Seat',
       '1 Pair of Jeans (Levis 501 Or Similar)',
       '1 Summer Dress in a Chain Store (Zara, H&M, ...)',
       '1 Pair of Nike Running Shoes (Mid-Range)',
       '1 Pair of Men Leather Business Shoes',
       'Price per Square Meter to Buy Apartment in City Centre',
       'Price per Square Meter to Buy Apartment Outside of Centre',
       'Average Monthly Net Salary (After Tax)',
       'Mortgage Interest Rate in Percentages (%), Yearly, for 20 Years Fixed-Rate',
       'Taxi Start (Normal Tariff)', 'Taxi 1km (Normal Tariff)',
       'Taxi 1hour Waiting (Normal Tariff)', 'Apples (1kg)', 'Oranges (1kg)',
       'Potato (1kg)', 'Lettuce (1 head)', 'Cappuccino (regular)',
       'Rice (white), (1kg)', 'Tomato (1kg)', 'Banana (1kg)', 'Onion (1kg)',
       'Beef Round (1kg) (or Equivalent Back Leg Red Meat)',
       'Toyota Corolla 1.6l 97kW Comfort (Or Equivalent New Car)',
       'Preschool (or Kindergarten), Full Day, Private, Monthly for 1 Child',
       'International Primary School, Yearly for 1 Child', 'Country', 'City'],
      dtype='object')

In [42]:
# save new csv as cost_living_clean
cost_living.to_csv('cost_living_clean.csv')